---
# tasks file for roles/haproxy
    - name: ensure httpd services is installed
      yum: 
        name: httpd
        state: latest

    - name: fierwalld enable
      firewalld:
        service: http
        permanent: true
        state: enabled

    - name: reload service firewalld
      systemd:
        name: firewalld
        state: reloaded

    - name: Install host1 yum utils
      yum:
        name: haproxy
        state: latest
      become: yes

    - name: deploy template
      template:
        src: haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg

    - name: service start
      service:
        name: haproxy
        state: started
        enabled: true
