---
- name: display fact
  hosts: host1
  tasks:
    - name: msg
      debug:
        var: ansible_facts

    - name: new
      debug:
        var: ansible_facts.distribution

    - name: legacy
      debug:
        var: ansible.distribution
