- name: "APT - Add Docker GPG key"
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: "APT - Add Docker repository"
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
    state: present
    filename: docker
    mode: '0666'

- name: "APT - install misc packages"
  apt:
    name: "{{ item }}"
    update_cache: yes
  loop:
    - aptitude
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common

- name: "APT - install 'docker-ce'"
  apt:
    name: "docker-ce"
    update_cache: yes